export const lang: string = 'fr-fr'
export const API_KEY = import.meta.env.VITE_API_KEY
export const BASE_URL = import.meta.env.VITE_BASE_URL
export const IMAGE_URL = import.meta.env.VITE_IMAGE_URL
export const AUTH_URL = import.meta.env.VITE_AUTH_URL
export const IMAGE_URL_ORIGINAL = `${IMAGE_URL}/original`
export const IMAGE_URL_PATH400 = `${IMAGE_URL}/w400`
export const TYPE_TV = 'tv'
export const TYPE_MOVIE = 'movie'
export const localStorageTokenKey = 'netflix_auth_token'